apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ghcr.io/hinco114/230620-telepresence
          imagePullPolicy: Always
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: REDIS_ENDPOINT
              value: 'redis://elasticache-cluster-demo.2lqmsy.0001.apn2.cache.amazonaws.com:6379'
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    app: web
  type: NodePort
