apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: telepresence-test
  region: ap-northeast-2

vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  subnets:
    private:
      ap-northeast-2a:
        id: subnet-0caf48a84ee59cd40
      ap-northeast-2b:
        id: subnet-0cff78d31fe74ba5e
    public:
      ap-northeast-2a:
        id: subnet-071213ff800e42572
      ap-northeast-2b:
        id: subnet-0c272e41ab8fde274

managedNodeGroups:
  - name: ng-1
    instanceSelector:
      vCPUs: 2
      memory: "4" # 4 GiB, unit defaults to GiB
    spot: true
    desiredCapacity: 1
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
    iam:
      withAddonPolicies:
        autoScaler: true
    privateNetworking: true
    securityGroups:
      attachIDs:
        - sg-0ee4684d1dbf88e3a
    subnets:
      - subnet-071213ff800e42572
